"""
Тесты для backend.generator.prompt_builder (PromptBuilder, не NewPromptBuilder).
"""
import pytest
from unittest.mock import MagicMock, patch

from backend.generator.prompt_builder import PromptBuilder


@pytest.fixture
def templates_json(tmp_path):
    import json
    data = {"templates": {"t1": {"name": "Template 1"}}}
    path = tmp_path / "templates.json"
    path.write_text(json.dumps(data), encoding="utf-8")
    return str(path)


class TestPromptBuilder:
    def test_build_prompt_with_landing_type_delegates_to_new_builder(self, templates_json):
        with patch.object(PromptBuilder, "__init__", lambda self, templates_path=None: None):
            builder = PromptBuilder.__new__(PromptBuilder)
            builder.template_loader = MagicMock()
            builder.new_prompt_builder = MagicMock()
            builder.new_prompt_builder.build_prompt.return_value = "Generated by new builder"
            user_data = {"landing_type": "single_product", "product_name": "X"}
            result = builder.build_prompt("t1", user_data)
            assert result == "Generated by new builder"
            builder.new_prompt_builder.build_prompt.assert_called_once_with(user_data)

    def test_build_prompt_without_landing_type_uses_detailed_prompt(self, templates_json):
        builder = PromptBuilder(templates_path=templates_json)
        user_data = {"product_name": "Товар", "product_description": "Описание", "old_price": "100", "new_price": "80"}
        result = builder.build_prompt("t1", user_data)
        assert "Товар" in result
        assert "100" in result or "80" in result
        assert "ЗАДАЧА" in result or "лендинг" in result.lower()
